version: '3'

networks:
  monitoring:

    null
services:

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - monitoring

  prometheus:
    build: ./prometheus
    image: irrigation-springler-log-monitor/prometheus
    ports:
      - 9090:9090
    networks:
      - monitoring
